/** \file
 *  This C source file was generated by $ANTLR version 3.3 Nov 30, 2010 12:45:30
 *
 *     -  From the grammar source file : LinearGradientColor.g
 *     -                            On : 2011-09-23 20:02:23
 *     -                for the parser : LinearGradientColorParserParser *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "LinearGradientColorParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define     CTX ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef  SCOPE_TYPE
#undef  SCOPE_STACK
#undef  SCOPE_TOP
#define SCOPE_TYPE(scope)   pLinearGradientColorParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pLinearGradientColorParser_##scope##Stack
#define SCOPE_TOP(scope)    ctx->pLinearGradientColorParser_##scope##Top
#define SCOPE_SIZE(scope)       ctx->pLinearGradientColorParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)    (ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef      PARSER
#undef      RECOGNIZER
#undef      HAVEPARSEDRULE
#undef      MEMOIZE
#undef      INPUT
#undef      STRSTREAM
#undef      HASEXCEPTION
#undef      EXCEPTION
#undef      MATCHT
#undef      MATCHANYT
#undef      FOLLOWSTACK
#undef      FOLLOWPUSH
#undef      FOLLOWPOP
#undef      PRECOVER
#undef      PREPORTERROR
#undef      LA
#undef      LT
#undef      CONSTRUCTEX
#undef      CONSUME
#undef      MARK
#undef      REWIND
#undef      REWINDLAST
#undef      PERRORRECOVERY
#undef      HASFAILED
#undef      FAILEDFLAG
#undef      RECOVERFROMMISMATCHEDSET
#undef      RECOVERFROMMISMATCHEDELEMENT
#undef      INDEX
#undef      ADAPTOR
#undef      SEEK
#undef      RULEMEMO
#undef      DBG

#define     PARSER              ctx->pParser
#define     RECOGNIZER              PARSER->rec
#define     PSRSTATE                RECOGNIZER->state
#define     HAVEPARSEDRULE(r)           RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define     MEMOIZE(ri,si)          RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define     INPUT               PARSER->tstream
#define     STRSTREAM               INPUT
#define     ISTREAM             INPUT->istream
#define     INDEX()             ISTREAM->index(INPUT->istream)
#define     HASEXCEPTION()          (PSRSTATE->error == ANTLR3_TRUE)
#define     EXCEPTION               PSRSTATE->exception
#define     MATCHT(t, fs)           RECOGNIZER->match(RECOGNIZER, t, fs)
#define     MATCHANYT()             RECOGNIZER->matchAny(RECOGNIZER)
#define     FOLLOWSTACK             PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define     FOLLOWPUSH(x)
#define     FOLLOWPOP()
#else
#define     FOLLOWPUSH(x)           FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define     FOLLOWPOP()             FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define     PRECOVER()              RECOGNIZER->recover(RECOGNIZER)
#define     PREPORTERROR()          RECOGNIZER->reportError(RECOGNIZER)
#define     LA(n)               INPUT->istream->_LA(ISTREAM, n)
#define     LT(n)               INPUT->_LT(INPUT, n)
#define     CONSTRUCTEX()           RECOGNIZER->exConstruct(RECOGNIZER)
#define     CONSUME()               ISTREAM->consume(ISTREAM)
#define     MARK()              ISTREAM->mark(ISTREAM)
#define     REWIND(m)               ISTREAM->rewind(ISTREAM, m)
#define     REWINDLAST()            ISTREAM->rewindLast(ISTREAM)
#define     SEEK(n)             ISTREAM->seek(ISTREAM, n)
#define     PERRORRECOVERY          PSRSTATE->errorRecovery
#define     FAILEDFLAG              PSRSTATE->failed
#define     HASFAILED()             (FAILEDFLAG == ANTLR3_TRUE)
#define     BACKTRACKING            PSRSTATE->backtracking
#define     RECOVERFROMMISMATCHEDSET(s)     RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define     RECOVERFROMMISMATCHEDELEMENT(e) RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define     RULEMEMO                        PSRSTATE->ruleMemo
#define     DBG                             RECOGNIZER->debugger

#define     TOKTEXT(tok, txt)               tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define     UP      ANTLR3_TOKEN_UP
#define     DOWN    ANTLR3_TOKEN_DOWN
#define     EOR     ANTLR3_TOKEN_EOR
#define     INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */


/* globalAttributeScopeFuncDecl(scope)
 */
/* -----------------------------------------------------------------------------
 * Function declaration for creating a LinearGradientColorParser_ColorSet scope set
 */
static pLinearGradientColorParser_ColorSet_SCOPE   pLinearGradientColorParser_ColorSetPush(pLinearGradientColorParser ctx);
static void ANTLR3_CDECL ColorSetFree(pLinearGradientColorParser_ColorSet_SCOPE scope);
/* ----------------------------------------------------------------------------- */

/* globalAttributeScopeFuncs(scope)
 */
/* attributeFuncs(scope)
 */

static void ANTLR3_CDECL ColorSetFree(pLinearGradientColorParser_ColorSet_SCOPE scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Allocate initial memory for a LinearGradientColorParser ColorSet scope variable stack entry and
 *         add it to the top of the stack.
 *
 * \remark
 * By default the structure is freed with ANTLR_FREE(), but you can use the
 * the \@init action to install a pointer to a custom free() routine by
 * adding the code:
 * \code
 *   ctx->pLinearGradientColorParser_ColorSetTop->free = myroutine;
 * \endcode
 *
 * With lots of comments of course! The routine should be declared in
 * \@members { } as:
 * \code
 *   void ANTLR3_CDECL myfunc( pLinearGradientColorParser_ColorSet_SCOPE ptr).
 * \endcode
 *
 * It should perform any custom freeing stuff that you need (call ANTLR_FREE3, not free()
 * NB: It should not free the pointer it is given, which is the scope stack entry itself
 * and will be freed by the function that calls your custom free routine.
 *
 */
static pLinearGradientColorParser_ColorSet_SCOPE
pLinearGradientColorParser_ColorSetPush(pLinearGradientColorParser ctx)
{
    /* Pointer used to create a new set of attributes
     */
    pLinearGradientColorParser_ColorSet_SCOPE      newAttributes;

    /* Allocate the memory for a new structure if we need one.
     */
    if (ctx->pLinearGradientColorParser_ColorSetStack->size(ctx->pLinearGradientColorParser_ColorSetStack) > ctx->pLinearGradientColorParser_ColorSetStack_limit) {
        // The current limit value was less than the number of scopes available on the stack so
        // we can just reuse one. Our limit tracks the stack count, so the index of the entry we want
        // is one less than that, or conveniently, the current value of limit.
        //
        newAttributes = (pLinearGradientColorParser_ColorSet_SCOPE)ctx->pLinearGradientColorParser_ColorSetStack->get(ctx->pLinearGradientColorParser_ColorSetStack, ctx->pLinearGradientColorParser_ColorSetStack_limit);
    } else {
        // Need a new allocation
        //
        newAttributes = (pLinearGradientColorParser_ColorSet_SCOPE) ANTLR3_MALLOC(sizeof(LinearGradientColorParser_ColorSet_SCOPE));
        if  (newAttributes != NULL) {
            /* Standard ANTLR3 library implementation
             */
            ctx->pLinearGradientColorParser_ColorSetStack->push(ctx->pLinearGradientColorParser_ColorSetStack, newAttributes, (void (*)(void *))ColorSetFree);
        }
    }

    // Blank out any previous free pointer, the user might or might install a new one.
    //
    newAttributes->free = NULL;

    // Indicate the position in the available stack that the current level is at
    //
    ctx->pLinearGradientColorParser_ColorSetStack_limit++;

    /* Return value is the pointer to the new entry, which may be used locally
     * without de-referencing via the context.
     */
    return  newAttributes;
}



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   LinearGradientColorParserTokenNames[21 + 4]
= {
    (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
    (pANTLR3_UINT8) "<EOR>",
    (pANTLR3_UINT8) "<DOWN>",
    (pANTLR3_UINT8) "<UP>",
    (pANTLR3_UINT8) "ID",
    (pANTLR3_UINT8) "HEX_DIGIT",
    (pANTLR3_UINT8) "HEXINT",
    (pANTLR3_UINT8) "EXPONENT",
    (pANTLR3_UINT8) "FLOAT",
    (pANTLR3_UINT8) "COMMENT",
    (pANTLR3_UINT8) "WS",
    (pANTLR3_UINT8) "ESC_SEQ",
    (pANTLR3_UINT8) "STRING",
    (pANTLR3_UINT8) "UNICODE_ESC",
    (pANTLR3_UINT8) "OCTAL_ESC",
    (pANTLR3_UINT8) "':'",
    (pANTLR3_UINT8) "'-'",
    (pANTLR3_UINT8) "'TOP_BOTTOM'",
    (pANTLR3_UINT8) "'TOPLEFT_BOTTOMRIGHT'",
    (pANTLR3_UINT8) "'TOPRIGHT_TO_BOTTOMLEFT'",
    (pANTLR3_UINT8) "'@'",
    (pANTLR3_UINT8) "'rgba('",
    (pANTLR3_UINT8) "','",
    (pANTLR3_UINT8) "')'",
    (pANTLR3_UINT8) "'hsba('"
};


/* globalAttributeScopeFuncMacro(scope)
 */
/** Function  for popping the top value from a pLinearGradientColorParser_ColorSetStack
 */
void
pLinearGradientColorParser_ColorSetPop(pLinearGradientColorParser ctx)
{
    // First see if the user defined a function they want to be called when a
    // scope is popped/freed.
    //
    // If the user supplied the scope entries with a free function,then call it first
    //
    if  (SCOPE_TOP(ColorSet)->free != NULL) {
        SCOPE_TOP(ColorSet)->free(SCOPE_TOP(ColorSet));
    }

    // Now we decrement the scope's upper limit bound. We do not actually pop the scope as
    // we want to reuse scope entries if we do continuous push and pops. Most scopes don't
    // next too far so we don't want to keep freeing and allocating them
    //
    ctx->pLinearGradientColorParser_ColorSetStack_limit--;
    SCOPE_TOP(ColorSet) = (pLinearGradientColorParser_ColorSet_SCOPE)(ctx->pLinearGradientColorParser_ColorSetStack->get(ctx->pLinearGradientColorParser_ColorSetStack, ctx->pLinearGradientColorParser_ColorSetStack_limit - 1));
}

// Forward declare the locally static matching functions we have generated.
//
static nx::color::LinearGradientColor*  linearColor    (pLinearGradientColorParser ctx);
static void linearColorDirection    (pLinearGradientColorParser ctx);
static void linerColorElement    (pLinearGradientColorParser ctx);
static void rgba    (pLinearGradientColorParser ctx);
static void hsba    (pLinearGradientColorParser ctx);
static void pos    (pLinearGradientColorParser ctx);
static void LinearGradientColorParserFree(pLinearGradientColorParser ctx);
static void     LinearGradientColorParserReset (pLinearGradientColorParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static  void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "LinearGradientColor.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
    return fileName;
}
/** \brief Create a new LinearGradientColorParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pLinearGradientColorParser
LinearGradientColorParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
    // See if we can create a new parser with the standard constructor
    //
    return LinearGradientColorParserNewSSD(instream, NULL);
}

/** \brief Create a new LinearGradientColorParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pLinearGradientColorParser
LinearGradientColorParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pLinearGradientColorParser ctx;     /* Context structure we will build and return   */

    ctx = (pLinearGradientColorParser) ANTLR3_CALLOC(1, sizeof(LinearGradientColorParser));

    if  (ctx == NULL) {
        // Failed to allocate memory for parser context
        //
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in LinearGradientColorParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser        = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our LinearGradientColorParser interface
     */
    ctx->linearColor    = linearColor;
    ctx->linearColorDirection   = linearColorDirection;
    ctx->linerColorElement  = linerColorElement;
    ctx->rgba   = rgba;
    ctx->hsba   = hsba;
    ctx->pos    = pos;
    ctx->free           = LinearGradientColorParserFree;
    ctx->reset          = LinearGradientColorParserReset;
    ctx->getGrammarFileName = getGrammarFileName;

    /* Install the scope pushing methods.
     */
    /* globalAttributeScope(scope)
     */
    ctx->pLinearGradientColorParser_ColorSetPush     = pLinearGradientColorParser_ColorSetPush;
    ctx->pLinearGradientColorParser_ColorSetStack    = antlr3StackNew(0);
    ctx->pLinearGradientColorParser_ColorSetStack_limit    = 0;
    ctx->pLinearGradientColorParser_ColorSetTop      = NULL;






    /* Install the token table
     */
    PSRSTATE->tokenNames   = LinearGradientColorParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
LinearGradientColorParserReset (pLinearGradientColorParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
static void
LinearGradientColorParserFree(pLinearGradientColorParser ctx)
{
    /* Free any scope memory
     */
    /* globalAttributeScope(scope)
     */
    ctx->pLinearGradientColorParser_ColorSetStack->free(ctx->pLinearGradientColorParser_ColorSetStack);



    // Free this parser
    //
    ctx->pParser->free(ctx->pParser);

    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
}

/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
    return LinearGradientColorParserTokenNames;
}


/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_linearColorDirection_in_linearColor613  */
static  ANTLR3_BITWORD FOLLOW_linearColorDirection_in_linearColor613_bits[] = { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_linearColorDirection_in_linearColor613    = { FOLLOW_linearColorDirection_in_linearColor613_bits, 1   };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_linearColor615  */
static  ANTLR3_BITWORD FOLLOW_15_in_linearColor615_bits[]   = { ANTLR3_UINT64_LIT(0x0000000001200000) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_linearColor615  = { FOLLOW_15_in_linearColor615_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_linerColorElement_in_linearColor617  */
static  ANTLR3_BITWORD FOLLOW_linerColorElement_in_linearColor617_bits[]    = { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_linerColorElement_in_linearColor617   = { FOLLOW_linerColorElement_in_linearColor617_bits, 1  };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_linearColor620  */
static  ANTLR3_BITWORD FOLLOW_16_in_linearColor620_bits[]   = { ANTLR3_UINT64_LIT(0x0000000001200000) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_linearColor620  = { FOLLOW_16_in_linearColor620_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_linerColorElement_in_linearColor622  */
static  ANTLR3_BITWORD FOLLOW_linerColorElement_in_linearColor622_bits[]    = { ANTLR3_UINT64_LIT(0x0000000000010002) };
static  ANTLR3_BITSET_LIST FOLLOW_linerColorElement_in_linearColor622   = { FOLLOW_linerColorElement_in_linearColor622_bits, 1  };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_linearColorDirection640  */
static  ANTLR3_BITWORD FOLLOW_set_in_linearColorDirection640_bits[] = { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_linearColorDirection640    = { FOLLOW_set_in_linearColorDirection640_bits, 1   };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_rgba_in_linerColorElement666  */
static  ANTLR3_BITWORD FOLLOW_rgba_in_linerColorElement666_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_rgba_in_linerColorElement666  = { FOLLOW_rgba_in_linerColorElement666_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_hsba_in_linerColorElement670  */
static  ANTLR3_BITWORD FOLLOW_hsba_in_linerColorElement670_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_hsba_in_linerColorElement670  = { FOLLOW_hsba_in_linerColorElement670_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_linerColorElement674  */
static  ANTLR3_BITWORD FOLLOW_20_in_linerColorElement674_bits[] = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_linerColorElement674    = { FOLLOW_20_in_linerColorElement674_bits, 1   };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_pos_in_linerColorElement676  */
static  ANTLR3_BITWORD FOLLOW_pos_in_linerColorElement676_bits[]    = { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_pos_in_linerColorElement676   = { FOLLOW_pos_in_linerColorElement676_bits, 1  };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_21_in_rgba691  */
static  ANTLR3_BITWORD FOLLOW_21_in_rgba691_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_21_in_rgba691 = { FOLLOW_21_in_rgba691_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_rgba695  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_rgba695_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_rgba695  = { FOLLOW_FLOAT_in_rgba695_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_rgba697  */
static  ANTLR3_BITWORD FOLLOW_22_in_rgba697_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_rgba697 = { FOLLOW_22_in_rgba697_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_rgba701  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_rgba701_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_rgba701  = { FOLLOW_FLOAT_in_rgba701_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_rgba703  */
static  ANTLR3_BITWORD FOLLOW_22_in_rgba703_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_rgba703 = { FOLLOW_22_in_rgba703_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_rgba707  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_rgba707_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_rgba707  = { FOLLOW_FLOAT_in_rgba707_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_rgba709  */
static  ANTLR3_BITWORD FOLLOW_22_in_rgba709_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_rgba709 = { FOLLOW_22_in_rgba709_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_rgba713  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_rgba713_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000800000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_rgba713  = { FOLLOW_FLOAT_in_rgba713_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_23_in_rgba715  */
static  ANTLR3_BITWORD FOLLOW_23_in_rgba715_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_23_in_rgba715 = { FOLLOW_23_in_rgba715_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_21_in_rgba726  */
static  ANTLR3_BITWORD FOLLOW_21_in_rgba726_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_21_in_rgba726 = { FOLLOW_21_in_rgba726_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_HEXINT_in_rgba730  */
static  ANTLR3_BITWORD FOLLOW_HEXINT_in_rgba730_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_HEXINT_in_rgba730 = { FOLLOW_HEXINT_in_rgba730_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_rgba732  */
static  ANTLR3_BITWORD FOLLOW_22_in_rgba732_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_rgba732 = { FOLLOW_22_in_rgba732_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_rgba736  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_rgba736_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000800000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_rgba736  = { FOLLOW_FLOAT_in_rgba736_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_23_in_rgba738  */
static  ANTLR3_BITWORD FOLLOW_23_in_rgba738_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_23_in_rgba738 = { FOLLOW_23_in_rgba738_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_24_in_hsba753  */
static  ANTLR3_BITWORD FOLLOW_24_in_hsba753_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_24_in_hsba753 = { FOLLOW_24_in_hsba753_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_hsba757  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_hsba757_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_hsba757  = { FOLLOW_FLOAT_in_hsba757_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_hsba759  */
static  ANTLR3_BITWORD FOLLOW_22_in_hsba759_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_hsba759 = { FOLLOW_22_in_hsba759_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_hsba763  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_hsba763_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_hsba763  = { FOLLOW_FLOAT_in_hsba763_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_hsba765  */
static  ANTLR3_BITWORD FOLLOW_22_in_hsba765_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_hsba765 = { FOLLOW_22_in_hsba765_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_hsba769  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_hsba769_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_hsba769  = { FOLLOW_FLOAT_in_hsba769_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_hsba771  */
static  ANTLR3_BITWORD FOLLOW_22_in_hsba771_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_hsba771 = { FOLLOW_22_in_hsba771_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_hsba775  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_hsba775_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000800000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_hsba775  = { FOLLOW_FLOAT_in_hsba775_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_23_in_hsba777  */
static  ANTLR3_BITWORD FOLLOW_23_in_hsba777_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_23_in_hsba777 = { FOLLOW_23_in_hsba777_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_pos792  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_pos792_bits[]    = { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_pos792   = { FOLLOW_FLOAT_in_pos792_bits, 1  };




/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start linearColor
 * LinearGradientColor.g:112:1: linearColor returns [nx::color::LinearGradientColor* ret] : linearColorDirection ':' linerColorElement ( '-' linerColorElement )+ ;
 */
static nx::color::LinearGradientColor*
linearColor(pLinearGradientColorParser ctx)
{
    nx::color::LinearGradientColor* ret;

    /* Initialize rule variables
     */
    ctx->pLinearGradientColorParser_ColorSetTop = pLinearGradientColorParser_ColorSetPush(ctx);


    (SCOPE_TOP(ColorSet))->color = new nx::color::LinearGradientColor();

    {
        // LinearGradientColor.g:117:2: ( linearColorDirection ':' linerColorElement ( '-' linerColorElement )+ )
        // LinearGradientColor.g:118:2: linearColorDirection ':' linerColorElement ( '-' linerColorElement )+
        {
            FOLLOWPUSH(FOLLOW_linearColorDirection_in_linearColor613);
            linearColorDirection(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION()) {
                goto rulelinearColorEx;
            }

            MATCHT(15, &FOLLOW_15_in_linearColor615);
            if  (HASEXCEPTION()) {
                goto rulelinearColorEx;
            }

            FOLLOWPUSH(FOLLOW_linerColorElement_in_linearColor617);
            linerColorElement(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION()) {
                goto rulelinearColorEx;
            }

            // LinearGradientColor.g:118:45: ( '-' linerColorElement )+
            {
                int cnt1 = 0;

                for (;;) {
                    int alt1 = 2;
                    switch ( LA(1) ) {
                    case 16: {
                        alt1 = 1;
                    }
                    break;

                    }

                    switch (alt1) {
                    case 1:
                        // LinearGradientColor.g:118:46: '-' linerColorElement
                    {
                        MATCHT(16, &FOLLOW_16_in_linearColor620);
                        if  (HASEXCEPTION()) {
                            goto rulelinearColorEx;
                        }

                        FOLLOWPUSH(FOLLOW_linerColorElement_in_linearColor622);
                        linerColorElement(ctx);

                        FOLLOWPOP();
                        if  (HASEXCEPTION()) {
                            goto rulelinearColorEx;
                        }


                    }
                    break;

                    default:

                        if ( cnt1 >= 1 ) {
                            goto loop1;
                        }
                        /* mismatchedSetEx()
                         */
                        CONSTRUCTEX();
                        EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
                        EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


                        goto rulelinearColorEx;
                    }
                    cnt1++;
                }
loop1: ;    /* Jump to here if this rule does not match */
            }
            {

                ret =    (SCOPE_TOP(ColorSet))->color;

            }

        }

    }


    // This is where rules clean up and exit
    //
    goto rulelinearColorEx; /* Prevent compiler warnings */
rulelinearColorEx:
    ;

    if (HASEXCEPTION()) {
        PREPORTERROR();
        PRECOVER();
    }

    pLinearGradientColorParser_ColorSetPop(ctx);

    return ret;
}
/* $ANTLR end linearColor */

/**
 * $ANTLR start linearColorDirection
 * LinearGradientColor.g:124:1: linearColorDirection : direction= ( 'TOP_BOTTOM' | 'TOPLEFT_BOTTOMRIGHT' | 'TOPRIGHT_TO_BOTTOMLEFT' ) ;
 */
static void
linearColorDirection(pLinearGradientColorParser ctx)
{
    pANTLR3_COMMON_TOKEN    direction;

    /* Initialize rule variables
     */


    direction       = NULL;

    {
        // LinearGradientColor.g:125:2: (direction= ( 'TOP_BOTTOM' | 'TOPLEFT_BOTTOMRIGHT' | 'TOPRIGHT_TO_BOTTOMLEFT' ) )
        // LinearGradientColor.g:125:4: direction= ( 'TOP_BOTTOM' | 'TOPLEFT_BOTTOMRIGHT' | 'TOPRIGHT_TO_BOTTOMLEFT' )
        {
            direction = (pANTLR3_COMMON_TOKEN)LT(1);
            if ( ((LA(1) >= 17) && (LA(1) <= 19)) ) {
                CONSUME();
                PERRORRECOVERY = ANTLR3_FALSE;
            } else {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = &FOLLOW_set_in_linearColorDirection640;
                RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_linearColorDirection640);
                goto rulelinearColorDirectionEx;
            }

            {

                if (wcscmp((wchar_t*)(direction->getText(direction))->chars, L"TOP_BOTTOM") == 0) {
                    (SCOPE_TOP(ColorSet))->color->SetGradientDirection(nx::color::GRADIENT_DIRECTION_TOP_BOTTOM);
                } else if (wcscmp((wchar_t*)(direction->getText(direction))->chars, L"TOPLEFT_BOTTOMRIGHT") == 0) {
                    (SCOPE_TOP(ColorSet))->color->SetGradientDirection(nx::color::GRADIENT_DIRECTION_TOPLEFT_TO_BOTTOMRIGHT);
                } else if (wcscmp((wchar_t*)(direction->getText(direction))->chars, L"TOPRIGHT_TO_BOTTOMLEFT") == 0) {
                    (SCOPE_TOP(ColorSet))->color->SetGradientDirection(nx::color::GRADIENT_DIRECTION_TOPRIGHT_TO_BOTTOMLEFT);
                }

            }

        }

    }


    // This is where rules clean up and exit
    //
    goto rulelinearColorDirectionEx; /* Prevent compiler warnings */
rulelinearColorDirectionEx:
    ;

    if (HASEXCEPTION()) {
        PREPORTERROR();
        PRECOVER();
    }


    return ;
}
/* $ANTLR end linearColorDirection */

/**
 * $ANTLR start linerColorElement
 * LinearGradientColor.g:139:1: linerColorElement : ( rgba | hsba ) '@' pos ;
 */
static void
linerColorElement(pLinearGradientColorParser ctx)
{
    /* Initialize rule variables
     */


    {
        // LinearGradientColor.g:139:19: ( ( rgba | hsba ) '@' pos )
        // LinearGradientColor.g:140:2: ( rgba | hsba ) '@' pos
        {

            // LinearGradientColor.g:140:2: ( rgba | hsba )
            {
                int alt2 = 2;
                switch ( LA(1) ) {
                case 21: {
                    alt2 = 1;
                }
                break;
                case 24: {
                    alt2 = 2;
                }
                break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 2;
                    EXCEPTION->state        = 0;


                    goto rulelinerColorElementEx;
                }

                switch (alt2) {
                case 1:
                    // LinearGradientColor.g:140:4: rgba
                {
                    FOLLOWPUSH(FOLLOW_rgba_in_linerColorElement666);
                    rgba(ctx);

                    FOLLOWPOP();
                    if  (HASEXCEPTION()) {
                        goto rulelinerColorElementEx;
                    }


                }
                break;
                case 2:
                    // LinearGradientColor.g:140:11: hsba
                {
                    FOLLOWPUSH(FOLLOW_hsba_in_linerColorElement670);
                    hsba(ctx);

                    FOLLOWPOP();
                    if  (HASEXCEPTION()) {
                        goto rulelinerColorElementEx;
                    }


                }
                break;

                }
            }
            MATCHT(20, &FOLLOW_20_in_linerColorElement674);
            if  (HASEXCEPTION()) {
                goto rulelinerColorElementEx;
            }

            FOLLOWPUSH(FOLLOW_pos_in_linerColorElement676);
            pos(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION()) {
                goto rulelinerColorElementEx;
            }

            {

                (SCOPE_TOP(ColorSet))->color->AddGradientStop(  (SCOPE_TOP(ColorSet))->position,    (SCOPE_TOP(ColorSet))->red,     (SCOPE_TOP(ColorSet))->green,   (SCOPE_TOP(ColorSet))->blue,    (SCOPE_TOP(ColorSet))->alpha);

            }

        }

    }


    // This is where rules clean up and exit
    //
    goto rulelinerColorElementEx; /* Prevent compiler warnings */
rulelinerColorElementEx:
    ;

    if (HASEXCEPTION()) {
        PREPORTERROR();
        PRECOVER();
    }


    return ;
}
/* $ANTLR end linerColorElement */

/**
 * $ANTLR start rgba
 * LinearGradientColor.g:145:1: rgba : ( ( 'rgba(' r= FLOAT ',' g= FLOAT ',' b= FLOAT ',' a= FLOAT ')' ) | ( 'rgba(' rgb= HEXINT ',' a= FLOAT ')' ) );
 */
static void
rgba(pLinearGradientColorParser ctx)
{
    pANTLR3_COMMON_TOKEN    r;
    pANTLR3_COMMON_TOKEN    g;
    pANTLR3_COMMON_TOKEN    b;
    pANTLR3_COMMON_TOKEN    a;
    pANTLR3_COMMON_TOKEN    rgb;

    /* Initialize rule variables
     */


    r       = NULL;
    g       = NULL;
    b       = NULL;
    a       = NULL;
    rgb       = NULL;

    {
        {
            //  LinearGradientColor.g:145:6: ( ( 'rgba(' r= FLOAT ',' g= FLOAT ',' b= FLOAT ',' a= FLOAT ')' ) | ( 'rgba(' rgb= HEXINT ',' a= FLOAT ')' ) )

            ANTLR3_UINT32 alt3;

            alt3 = 2;

            switch ( LA(1) ) {
            case 21: {
                switch ( LA(2) ) {
                case FLOAT: {
                    alt3 = 1;
                }
                break;
                case HEXINT: {
                    alt3 = 2;
                }
                break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 3;
                    EXCEPTION->state        = 1;


                    goto rulergbaEx;
                }

            }
            break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto rulergbaEx;
            }

            switch (alt3) {
            case 1:
                // LinearGradientColor.g:146:2: ( 'rgba(' r= FLOAT ',' g= FLOAT ',' b= FLOAT ',' a= FLOAT ')' )
            {
                // LinearGradientColor.g:146:2: ( 'rgba(' r= FLOAT ',' g= FLOAT ',' b= FLOAT ',' a= FLOAT ')' )
                // LinearGradientColor.g:146:3: 'rgba(' r= FLOAT ',' g= FLOAT ',' b= FLOAT ',' a= FLOAT ')'
                {
                    MATCHT(21, &FOLLOW_21_in_rgba691);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    r = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_rgba695);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    MATCHT(22, &FOLLOW_22_in_rgba697);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    g = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_rgba701);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    MATCHT(22, &FOLLOW_22_in_rgba703);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    b = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_rgba707);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    MATCHT(22, &FOLLOW_22_in_rgba709);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    a = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_rgba713);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    MATCHT(23, &FOLLOW_23_in_rgba715);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }


                }

                {

                    (SCOPE_TOP(ColorSet))->red = pu8tof((r->getText(r))->chars);
                    (SCOPE_TOP(ColorSet))->green = pu8tof((g->getText(g))->chars);
                    (SCOPE_TOP(ColorSet))->blue = pu8tof((b->getText(b))->chars);
                    (SCOPE_TOP(ColorSet))->alpha = pu8tof((a->getText(a))->chars);

                }

            }
            break;
            case 2:
                // LinearGradientColor.g:153:2: ( 'rgba(' rgb= HEXINT ',' a= FLOAT ')' )
            {
                // LinearGradientColor.g:153:2: ( 'rgba(' rgb= HEXINT ',' a= FLOAT ')' )
                // LinearGradientColor.g:153:3: 'rgba(' rgb= HEXINT ',' a= FLOAT ')'
                {
                    MATCHT(21, &FOLLOW_21_in_rgba726);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    rgb = (pANTLR3_COMMON_TOKEN) MATCHT(HEXINT, &FOLLOW_HEXINT_in_rgba730);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    MATCHT(22, &FOLLOW_22_in_rgba732);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    a = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_rgba736);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    MATCHT(23, &FOLLOW_23_in_rgba738);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }


                }

                {

                    parse3values((rgb->getText(rgb))->chars, &( (SCOPE_TOP(ColorSet))->red), &( (SCOPE_TOP(ColorSet))->green), &(   (SCOPE_TOP(ColorSet))->blue));
                    (SCOPE_TOP(ColorSet))->alpha = pu8tof((a->getText(a))->chars);

                }

            }
            break;

            }
        }
    }


    // This is where rules clean up and exit
    //
    goto rulergbaEx; /* Prevent compiler warnings */
rulergbaEx:
    ;

    if (HASEXCEPTION()) {
        PREPORTERROR();
        PRECOVER();
    }


    return ;
}
/* $ANTLR end rgba */

/**
 * $ANTLR start hsba
 * LinearGradientColor.g:159:1: hsba : 'hsba(' h= FLOAT ',' s= FLOAT ',' b= FLOAT ',' a= FLOAT ')' ;
 */
static void
hsba(pLinearGradientColorParser ctx)
{
    pANTLR3_COMMON_TOKEN    h;
    pANTLR3_COMMON_TOKEN    s;
    pANTLR3_COMMON_TOKEN    b;
    pANTLR3_COMMON_TOKEN    a;

    /* Initialize rule variables
     */


    h       = NULL;
    s       = NULL;
    b       = NULL;
    a       = NULL;

    {
        // LinearGradientColor.g:159:6: ( 'hsba(' h= FLOAT ',' s= FLOAT ',' b= FLOAT ',' a= FLOAT ')' )
        // LinearGradientColor.g:160:2: 'hsba(' h= FLOAT ',' s= FLOAT ',' b= FLOAT ',' a= FLOAT ')'
        {
            MATCHT(24, &FOLLOW_24_in_hsba753);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            h = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_hsba757);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            MATCHT(22, &FOLLOW_22_in_hsba759);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            s = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_hsba763);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            MATCHT(22, &FOLLOW_22_in_hsba765);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            b = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_hsba769);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            MATCHT(22, &FOLLOW_22_in_hsba771);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            a = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_hsba775);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            MATCHT(23, &FOLLOW_23_in_hsba777);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            {

                HsvToRgb(
                    pu8tof((h->getText(h))->chars),
                    pu8tof((s->getText(s))->chars),
                    pu8tof((b->getText(b))->chars),
                    (SCOPE_TOP(ColorSet))->red,
                    (SCOPE_TOP(ColorSet))->green,
                    (SCOPE_TOP(ColorSet))->blue);
                (SCOPE_TOP(ColorSet))->alpha = pu8tof((a->getText(a))->chars);

            }

        }

    }


    // This is where rules clean up and exit
    //
    goto rulehsbaEx; /* Prevent compiler warnings */
rulehsbaEx:
    ;

    if (HASEXCEPTION()) {
        PREPORTERROR();
        PRECOVER();
    }


    return ;
}
/* $ANTLR end hsba */

/**
 * $ANTLR start pos
 * LinearGradientColor.g:173:1: pos : value= FLOAT ;
 */
static void
pos(pLinearGradientColorParser ctx)
{
    pANTLR3_COMMON_TOKEN    value;

    /* Initialize rule variables
     */


    value       = NULL;

    {
        // LinearGradientColor.g:173:5: (value= FLOAT )
        // LinearGradientColor.g:173:7: value= FLOAT
        {
            value = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_pos792);
            if  (HASEXCEPTION()) {
                goto ruleposEx;
            }

            {

                (SCOPE_TOP(ColorSet))->position = pu8tof((value->getText(value))->chars);

            }

        }

    }


    // This is where rules clean up and exit
    //
    goto ruleposEx; /* Prevent compiler warnings */
ruleposEx:
    ;

    if (HASEXCEPTION()) {
        PREPORTERROR();
        PRECOVER();
    }


    return ;
}
/* $ANTLR end pos */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
