/** \file
 *  This C source file was generated by $ANTLR version 3.3 Nov 30, 2010 12:45:30
 *
 *     -  From the grammar source file : RadialGradientColor.g
 *     -                            On : 2011-09-23 20:02:24
 *     -                for the parser : RadialGradientColorParserParser *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "RadialGradientColorParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define     CTX ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef  SCOPE_TYPE
#undef  SCOPE_STACK
#undef  SCOPE_TOP
#define SCOPE_TYPE(scope)   pRadialGradientColorParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pRadialGradientColorParser_##scope##Stack
#define SCOPE_TOP(scope)    ctx->pRadialGradientColorParser_##scope##Top
#define SCOPE_SIZE(scope)       ctx->pRadialGradientColorParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)    (ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef      PARSER
#undef      RECOGNIZER
#undef      HAVEPARSEDRULE
#undef      MEMOIZE
#undef      INPUT
#undef      STRSTREAM
#undef      HASEXCEPTION
#undef      EXCEPTION
#undef      MATCHT
#undef      MATCHANYT
#undef      FOLLOWSTACK
#undef      FOLLOWPUSH
#undef      FOLLOWPOP
#undef      PRECOVER
#undef      PREPORTERROR
#undef      LA
#undef      LT
#undef      CONSTRUCTEX
#undef      CONSUME
#undef      MARK
#undef      REWIND
#undef      REWINDLAST
#undef      PERRORRECOVERY
#undef      HASFAILED
#undef      FAILEDFLAG
#undef      RECOVERFROMMISMATCHEDSET
#undef      RECOVERFROMMISMATCHEDELEMENT
#undef      INDEX
#undef      ADAPTOR
#undef      SEEK
#undef      RULEMEMO
#undef      DBG

#define     PARSER              ctx->pParser
#define     RECOGNIZER              PARSER->rec
#define     PSRSTATE                RECOGNIZER->state
#define     HAVEPARSEDRULE(r)           RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define     MEMOIZE(ri,si)          RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define     INPUT               PARSER->tstream
#define     STRSTREAM               INPUT
#define     ISTREAM             INPUT->istream
#define     INDEX()             ISTREAM->index(INPUT->istream)
#define     HASEXCEPTION()          (PSRSTATE->error == ANTLR3_TRUE)
#define     EXCEPTION               PSRSTATE->exception
#define     MATCHT(t, fs)           RECOGNIZER->match(RECOGNIZER, t, fs)
#define     MATCHANYT()             RECOGNIZER->matchAny(RECOGNIZER)
#define     FOLLOWSTACK             PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define     FOLLOWPUSH(x)
#define     FOLLOWPOP()
#else
#define     FOLLOWPUSH(x)           FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define     FOLLOWPOP()             FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define     PRECOVER()              RECOGNIZER->recover(RECOGNIZER)
#define     PREPORTERROR()          RECOGNIZER->reportError(RECOGNIZER)
#define     LA(n)               INPUT->istream->_LA(ISTREAM, n)
#define     LT(n)               INPUT->_LT(INPUT, n)
#define     CONSTRUCTEX()           RECOGNIZER->exConstruct(RECOGNIZER)
#define     CONSUME()               ISTREAM->consume(ISTREAM)
#define     MARK()              ISTREAM->mark(ISTREAM)
#define     REWIND(m)               ISTREAM->rewind(ISTREAM, m)
#define     REWINDLAST()            ISTREAM->rewindLast(ISTREAM)
#define     SEEK(n)             ISTREAM->seek(ISTREAM, n)
#define     PERRORRECOVERY          PSRSTATE->errorRecovery
#define     FAILEDFLAG              PSRSTATE->failed
#define     HASFAILED()             (FAILEDFLAG == ANTLR3_TRUE)
#define     BACKTRACKING            PSRSTATE->backtracking
#define     RECOVERFROMMISMATCHEDSET(s)     RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define     RECOVERFROMMISMATCHEDELEMENT(e) RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define     RULEMEMO                        PSRSTATE->ruleMemo
#define     DBG                             RECOGNIZER->debugger

#define     TOKTEXT(tok, txt)               tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define     UP      ANTLR3_TOKEN_UP
#define     DOWN    ANTLR3_TOKEN_DOWN
#define     EOR     ANTLR3_TOKEN_EOR
#define     INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */


/* globalAttributeScopeFuncDecl(scope)
 */
/* -----------------------------------------------------------------------------
 * Function declaration for creating a RadialGradientColorParser_ColorSet scope set
 */
static pRadialGradientColorParser_ColorSet_SCOPE   pRadialGradientColorParser_ColorSetPush(pRadialGradientColorParser ctx);
static void ANTLR3_CDECL ColorSetFree(pRadialGradientColorParser_ColorSet_SCOPE scope);
/* ----------------------------------------------------------------------------- */

/* globalAttributeScopeFuncs(scope)
 */
/* attributeFuncs(scope)
 */

static void ANTLR3_CDECL ColorSetFree(pRadialGradientColorParser_ColorSet_SCOPE scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Allocate initial memory for a RadialGradientColorParser ColorSet scope variable stack entry and
 *         add it to the top of the stack.
 *
 * \remark
 * By default the structure is freed with ANTLR_FREE(), but you can use the
 * the \@init action to install a pointer to a custom free() routine by
 * adding the code:
 * \code
 *   ctx->pRadialGradientColorParser_ColorSetTop->free = myroutine;
 * \endcode
 *
 * With lots of comments of course! The routine should be declared in
 * \@members { } as:
 * \code
 *   void ANTLR3_CDECL myfunc( pRadialGradientColorParser_ColorSet_SCOPE ptr).
 * \endcode
 *
 * It should perform any custom freeing stuff that you need (call ANTLR_FREE3, not free()
 * NB: It should not free the pointer it is given, which is the scope stack entry itself
 * and will be freed by the function that calls your custom free routine.
 *
 */
static pRadialGradientColorParser_ColorSet_SCOPE
pRadialGradientColorParser_ColorSetPush(pRadialGradientColorParser ctx)
{
    /* Pointer used to create a new set of attributes
     */
    pRadialGradientColorParser_ColorSet_SCOPE      newAttributes;

    /* Allocate the memory for a new structure if we need one.
     */
    if (ctx->pRadialGradientColorParser_ColorSetStack->size(ctx->pRadialGradientColorParser_ColorSetStack) > ctx->pRadialGradientColorParser_ColorSetStack_limit) {
        // The current limit value was less than the number of scopes available on the stack so
        // we can just reuse one. Our limit tracks the stack count, so the index of the entry we want
        // is one less than that, or conveniently, the current value of limit.
        //
        newAttributes = (pRadialGradientColorParser_ColorSet_SCOPE)ctx->pRadialGradientColorParser_ColorSetStack->get(ctx->pRadialGradientColorParser_ColorSetStack, ctx->pRadialGradientColorParser_ColorSetStack_limit);
    } else {
        // Need a new allocation
        //
        newAttributes = (pRadialGradientColorParser_ColorSet_SCOPE) ANTLR3_MALLOC(sizeof(RadialGradientColorParser_ColorSet_SCOPE));
        if  (newAttributes != NULL) {
            /* Standard ANTLR3 library implementation
             */
            ctx->pRadialGradientColorParser_ColorSetStack->push(ctx->pRadialGradientColorParser_ColorSetStack, newAttributes, (void (*)(void *))ColorSetFree);
        }
    }

    // Blank out any previous free pointer, the user might or might install a new one.
    //
    newAttributes->free = NULL;

    // Indicate the position in the available stack that the current level is at
    //
    ctx->pRadialGradientColorParser_ColorSetStack_limit++;

    /* Return value is the pointer to the new entry, which may be used locally
     * without de-referencing via the context.
     */
    return  newAttributes;
}



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   RadialGradientColorParserTokenNames[18 + 4]
= {
    (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
    (pANTLR3_UINT8) "<EOR>",
    (pANTLR3_UINT8) "<DOWN>",
    (pANTLR3_UINT8) "<UP>",
    (pANTLR3_UINT8) "ID",
    (pANTLR3_UINT8) "HEX_DIGIT",
    (pANTLR3_UINT8) "HEXINT",
    (pANTLR3_UINT8) "EXPONENT",
    (pANTLR3_UINT8) "FLOAT",
    (pANTLR3_UINT8) "COMMENT",
    (pANTLR3_UINT8) "WS",
    (pANTLR3_UINT8) "ESC_SEQ",
    (pANTLR3_UINT8) "STRING",
    (pANTLR3_UINT8) "UNICODE_ESC",
    (pANTLR3_UINT8) "OCTAL_ESC",
    (pANTLR3_UINT8) "','",
    (pANTLR3_UINT8) "':'",
    (pANTLR3_UINT8) "'-'",
    (pANTLR3_UINT8) "'@'",
    (pANTLR3_UINT8) "'rgba('",
    (pANTLR3_UINT8) "')'",
    (pANTLR3_UINT8) "'hsba('"
};


/* globalAttributeScopeFuncMacro(scope)
 */
/** Function  for popping the top value from a pRadialGradientColorParser_ColorSetStack
 */
void
pRadialGradientColorParser_ColorSetPop(pRadialGradientColorParser ctx)
{
    // First see if the user defined a function they want to be called when a
    // scope is popped/freed.
    //
    // If the user supplied the scope entries with a free function,then call it first
    //
    if  (SCOPE_TOP(ColorSet)->free != NULL) {
        SCOPE_TOP(ColorSet)->free(SCOPE_TOP(ColorSet));
    }

    // Now we decrement the scope's upper limit bound. We do not actually pop the scope as
    // we want to reuse scope entries if we do continuous push and pops. Most scopes don't
    // next too far so we don't want to keep freeing and allocating them
    //
    ctx->pRadialGradientColorParser_ColorSetStack_limit--;
    SCOPE_TOP(ColorSet) = (pRadialGradientColorParser_ColorSet_SCOPE)(ctx->pRadialGradientColorParser_ColorSetStack->get(ctx->pRadialGradientColorParser_ColorSetStack, ctx->pRadialGradientColorParser_ColorSetStack_limit - 1));
}

// Forward declare the locally static matching functions we have generated.
//
static nx::color::RadialGradientColor*  radialColor    (pRadialGradientColorParser ctx);
static void radialColorElement    (pRadialGradientColorParser ctx);
static void rgba    (pRadialGradientColorParser ctx);
static void hsba    (pRadialGradientColorParser ctx);
static void pos    (pRadialGradientColorParser ctx);
static void RadialGradientColorParserFree(pRadialGradientColorParser ctx);
static void     RadialGradientColorParserReset (pRadialGradientColorParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static  void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "RadialGradientColor.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
    return fileName;
}
/** \brief Create a new RadialGradientColorParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pRadialGradientColorParser
RadialGradientColorParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
    // See if we can create a new parser with the standard constructor
    //
    return RadialGradientColorParserNewSSD(instream, NULL);
}

/** \brief Create a new RadialGradientColorParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pRadialGradientColorParser
RadialGradientColorParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pRadialGradientColorParser ctx;     /* Context structure we will build and return   */

    ctx = (pRadialGradientColorParser) ANTLR3_CALLOC(1, sizeof(RadialGradientColorParser));

    if  (ctx == NULL) {
        // Failed to allocate memory for parser context
        //
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in RadialGradientColorParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser        = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our RadialGradientColorParser interface
     */
    ctx->radialColor    = radialColor;
    ctx->radialColorElement = radialColorElement;
    ctx->rgba   = rgba;
    ctx->hsba   = hsba;
    ctx->pos    = pos;
    ctx->free           = RadialGradientColorParserFree;
    ctx->reset          = RadialGradientColorParserReset;
    ctx->getGrammarFileName = getGrammarFileName;

    /* Install the scope pushing methods.
     */
    /* globalAttributeScope(scope)
     */
    ctx->pRadialGradientColorParser_ColorSetPush     = pRadialGradientColorParser_ColorSetPush;
    ctx->pRadialGradientColorParser_ColorSetStack    = antlr3StackNew(0);
    ctx->pRadialGradientColorParser_ColorSetStack_limit    = 0;
    ctx->pRadialGradientColorParser_ColorSetTop      = NULL;






    /* Install the token table
     */
    PSRSTATE->tokenNames   = RadialGradientColorParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
RadialGradientColorParserReset (pRadialGradientColorParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
static void
RadialGradientColorParserFree(pRadialGradientColorParser ctx)
{
    /* Free any scope memory
     */
    /* globalAttributeScope(scope)
     */
    ctx->pRadialGradientColorParser_ColorSetStack->free(ctx->pRadialGradientColorParser_ColorSetStack);



    // Free this parser
    //
    ctx->pParser->free(ctx->pParser);

    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
}

/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
    return RadialGradientColorParserTokenNames;
}


/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_radialColor615  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_radialColor615_bits[]    = { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_radialColor615   = { FOLLOW_FLOAT_in_radialColor615_bits, 1  };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_radialColor617  */
static  ANTLR3_BITWORD FOLLOW_15_in_radialColor617_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_radialColor617  = { FOLLOW_15_in_radialColor617_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_radialColor621  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_radialColor621_bits[]    = { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_radialColor621   = { FOLLOW_FLOAT_in_radialColor621_bits, 1  };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_radialColor623  */
static  ANTLR3_BITWORD FOLLOW_16_in_radialColor623_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000280000) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_radialColor623  = { FOLLOW_16_in_radialColor623_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_radialColorElement_in_radialColor625  */
static  ANTLR3_BITWORD FOLLOW_radialColorElement_in_radialColor625_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000020000) };
static  ANTLR3_BITSET_LIST FOLLOW_radialColorElement_in_radialColor625  = { FOLLOW_radialColorElement_in_radialColor625_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_radialColor628  */
static  ANTLR3_BITWORD FOLLOW_17_in_radialColor628_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000280000) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_radialColor628  = { FOLLOW_17_in_radialColor628_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_radialColorElement_in_radialColor630  */
static  ANTLR3_BITWORD FOLLOW_radialColorElement_in_radialColor630_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000020002) };
static  ANTLR3_BITSET_LIST FOLLOW_radialColorElement_in_radialColor630  = { FOLLOW_radialColorElement_in_radialColor630_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_rgba_in_radialColorElement648  */
static  ANTLR3_BITWORD FOLLOW_rgba_in_radialColorElement648_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_rgba_in_radialColorElement648 = { FOLLOW_rgba_in_radialColorElement648_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_hsba_in_radialColorElement652  */
static  ANTLR3_BITWORD FOLLOW_hsba_in_radialColorElement652_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_hsba_in_radialColorElement652 = { FOLLOW_hsba_in_radialColorElement652_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_radialColorElement656  */
static  ANTLR3_BITWORD FOLLOW_18_in_radialColorElement656_bits[]    = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_radialColorElement656   = { FOLLOW_18_in_radialColorElement656_bits, 1  };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_pos_in_radialColorElement658  */
static  ANTLR3_BITWORD FOLLOW_pos_in_radialColorElement658_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_pos_in_radialColorElement658  = { FOLLOW_pos_in_radialColorElement658_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_rgba673  */
static  ANTLR3_BITWORD FOLLOW_19_in_rgba673_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_rgba673 = { FOLLOW_19_in_rgba673_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_rgba677  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_rgba677_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_rgba677  = { FOLLOW_FLOAT_in_rgba677_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_rgba679  */
static  ANTLR3_BITWORD FOLLOW_15_in_rgba679_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_rgba679 = { FOLLOW_15_in_rgba679_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_rgba683  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_rgba683_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_rgba683  = { FOLLOW_FLOAT_in_rgba683_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_rgba685  */
static  ANTLR3_BITWORD FOLLOW_15_in_rgba685_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_rgba685 = { FOLLOW_15_in_rgba685_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_rgba689  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_rgba689_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_rgba689  = { FOLLOW_FLOAT_in_rgba689_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_rgba691  */
static  ANTLR3_BITWORD FOLLOW_15_in_rgba691_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_rgba691 = { FOLLOW_15_in_rgba691_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_rgba695  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_rgba695_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_rgba695  = { FOLLOW_FLOAT_in_rgba695_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_rgba697  */
static  ANTLR3_BITWORD FOLLOW_20_in_rgba697_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_rgba697 = { FOLLOW_20_in_rgba697_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_rgba708  */
static  ANTLR3_BITWORD FOLLOW_19_in_rgba708_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_rgba708 = { FOLLOW_19_in_rgba708_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_HEXINT_in_rgba712  */
static  ANTLR3_BITWORD FOLLOW_HEXINT_in_rgba712_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_HEXINT_in_rgba712 = { FOLLOW_HEXINT_in_rgba712_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_rgba714  */
static  ANTLR3_BITWORD FOLLOW_15_in_rgba714_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_rgba714 = { FOLLOW_15_in_rgba714_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_rgba718  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_rgba718_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_rgba718  = { FOLLOW_FLOAT_in_rgba718_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_rgba720  */
static  ANTLR3_BITWORD FOLLOW_20_in_rgba720_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_rgba720 = { FOLLOW_20_in_rgba720_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_21_in_hsba735  */
static  ANTLR3_BITWORD FOLLOW_21_in_hsba735_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_21_in_hsba735 = { FOLLOW_21_in_hsba735_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_hsba739  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_hsba739_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_hsba739  = { FOLLOW_FLOAT_in_hsba739_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_hsba741  */
static  ANTLR3_BITWORD FOLLOW_15_in_hsba741_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_hsba741 = { FOLLOW_15_in_hsba741_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_hsba745  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_hsba745_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_hsba745  = { FOLLOW_FLOAT_in_hsba745_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_hsba747  */
static  ANTLR3_BITWORD FOLLOW_15_in_hsba747_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_hsba747 = { FOLLOW_15_in_hsba747_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_hsba751  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_hsba751_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_hsba751  = { FOLLOW_FLOAT_in_hsba751_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_hsba753  */
static  ANTLR3_BITWORD FOLLOW_15_in_hsba753_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_hsba753 = { FOLLOW_15_in_hsba753_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_hsba757  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_hsba757_bits[]   = { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_hsba757  = { FOLLOW_FLOAT_in_hsba757_bits, 1 };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_hsba759  */
static  ANTLR3_BITWORD FOLLOW_20_in_hsba759_bits[]  = { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_hsba759 = { FOLLOW_20_in_hsba759_bits, 1    };
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_pos774  */
static  ANTLR3_BITWORD FOLLOW_FLOAT_in_pos774_bits[]    = { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_pos774   = { FOLLOW_FLOAT_in_pos774_bits, 1  };




/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start radialColor
 * RadialGradientColor.g:111:1: radialColor returns [nx::color::RadialGradientColor* ret] : offsetX= FLOAT ',' offsetY= FLOAT ':' radialColorElement ( '-' radialColorElement )+ ;
 */
static nx::color::RadialGradientColor*
radialColor(pRadialGradientColorParser ctx)
{
    nx::color::RadialGradientColor* ret;

    pANTLR3_COMMON_TOKEN    offsetX;
    pANTLR3_COMMON_TOKEN    offsetY;

    /* Initialize rule variables
     */
    ctx->pRadialGradientColorParser_ColorSetTop = pRadialGradientColorParser_ColorSetPush(ctx);


    (SCOPE_TOP(ColorSet))->color = new nx::color::RadialGradientColor();

    offsetX       = NULL;
    offsetY       = NULL;

    {
        // RadialGradientColor.g:116:2: (offsetX= FLOAT ',' offsetY= FLOAT ':' radialColorElement ( '-' radialColorElement )+ )
        // RadialGradientColor.g:117:2: offsetX= FLOAT ',' offsetY= FLOAT ':' radialColorElement ( '-' radialColorElement )+
        {
            offsetX = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_radialColor615);
            if  (HASEXCEPTION()) {
                goto ruleradialColorEx;
            }

            MATCHT(15, &FOLLOW_15_in_radialColor617);
            if  (HASEXCEPTION()) {
                goto ruleradialColorEx;
            }

            offsetY = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_radialColor621);
            if  (HASEXCEPTION()) {
                goto ruleradialColorEx;
            }

            MATCHT(16, &FOLLOW_16_in_radialColor623);
            if  (HASEXCEPTION()) {
                goto ruleradialColorEx;
            }

            FOLLOWPUSH(FOLLOW_radialColorElement_in_radialColor625);
            radialColorElement(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION()) {
                goto ruleradialColorEx;
            }

            // RadialGradientColor.g:117:57: ( '-' radialColorElement )+
            {
                int cnt1 = 0;

                for (;;) {
                    int alt1 = 2;
                    switch ( LA(1) ) {
                    case 17: {
                        alt1 = 1;
                    }
                    break;

                    }

                    switch (alt1) {
                    case 1:
                        // RadialGradientColor.g:117:58: '-' radialColorElement
                    {
                        MATCHT(17, &FOLLOW_17_in_radialColor628);
                        if  (HASEXCEPTION()) {
                            goto ruleradialColorEx;
                        }

                        FOLLOWPUSH(FOLLOW_radialColorElement_in_radialColor630);
                        radialColorElement(ctx);

                        FOLLOWPOP();
                        if  (HASEXCEPTION()) {
                            goto ruleradialColorEx;
                        }


                    }
                    break;

                    default:

                        if ( cnt1 >= 1 ) {
                            goto loop1;
                        }
                        /* mismatchedSetEx()
                         */
                        CONSTRUCTEX();
                        EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
                        EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


                        goto ruleradialColorEx;
                    }
                    cnt1++;
                }
loop1: ;    /* Jump to here if this rule does not match */
            }
            {

                (SCOPE_TOP(ColorSet))->color->SetOffsetRatio(pu8tof((offsetX->getText(offsetX))->chars), pu8tof((offsetY->getText(offsetY))->chars));
                ret =    (SCOPE_TOP(ColorSet))->color;

            }

        }

    }


    // This is where rules clean up and exit
    //
    goto ruleradialColorEx; /* Prevent compiler warnings */
ruleradialColorEx:
    ;

    if (HASEXCEPTION()) {
        PREPORTERROR();
        PRECOVER();
    }

    pRadialGradientColorParser_ColorSetPop(ctx);

    return ret;
}
/* $ANTLR end radialColor */

/**
 * $ANTLR start radialColorElement
 * RadialGradientColor.g:124:1: radialColorElement : ( rgba | hsba ) '@' pos ;
 */
static void
radialColorElement(pRadialGradientColorParser ctx)
{
    /* Initialize rule variables
     */


    {
        // RadialGradientColor.g:124:20: ( ( rgba | hsba ) '@' pos )
        // RadialGradientColor.g:125:2: ( rgba | hsba ) '@' pos
        {

            // RadialGradientColor.g:125:2: ( rgba | hsba )
            {
                int alt2 = 2;
                switch ( LA(1) ) {
                case 19: {
                    alt2 = 1;
                }
                break;
                case 21: {
                    alt2 = 2;
                }
                break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 2;
                    EXCEPTION->state        = 0;


                    goto ruleradialColorElementEx;
                }

                switch (alt2) {
                case 1:
                    // RadialGradientColor.g:125:4: rgba
                {
                    FOLLOWPUSH(FOLLOW_rgba_in_radialColorElement648);
                    rgba(ctx);

                    FOLLOWPOP();
                    if  (HASEXCEPTION()) {
                        goto ruleradialColorElementEx;
                    }


                }
                break;
                case 2:
                    // RadialGradientColor.g:125:11: hsba
                {
                    FOLLOWPUSH(FOLLOW_hsba_in_radialColorElement652);
                    hsba(ctx);

                    FOLLOWPOP();
                    if  (HASEXCEPTION()) {
                        goto ruleradialColorElementEx;
                    }


                }
                break;

                }
            }
            MATCHT(18, &FOLLOW_18_in_radialColorElement656);
            if  (HASEXCEPTION()) {
                goto ruleradialColorElementEx;
            }

            FOLLOWPUSH(FOLLOW_pos_in_radialColorElement658);
            pos(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION()) {
                goto ruleradialColorElementEx;
            }

            {

                (SCOPE_TOP(ColorSet))->color->AddGradientStop(  (SCOPE_TOP(ColorSet))->position,    (SCOPE_TOP(ColorSet))->red,     (SCOPE_TOP(ColorSet))->green,   (SCOPE_TOP(ColorSet))->blue,    (SCOPE_TOP(ColorSet))->alpha);

            }

        }

    }


    // This is where rules clean up and exit
    //
    goto ruleradialColorElementEx; /* Prevent compiler warnings */
ruleradialColorElementEx:
    ;

    if (HASEXCEPTION()) {
        PREPORTERROR();
        PRECOVER();
    }


    return ;
}
/* $ANTLR end radialColorElement */

/**
 * $ANTLR start rgba
 * RadialGradientColor.g:130:1: rgba : ( ( 'rgba(' r= FLOAT ',' g= FLOAT ',' b= FLOAT ',' a= FLOAT ')' ) | ( 'rgba(' rgb= HEXINT ',' a= FLOAT ')' ) );
 */
static void
rgba(pRadialGradientColorParser ctx)
{
    pANTLR3_COMMON_TOKEN    r;
    pANTLR3_COMMON_TOKEN    g;
    pANTLR3_COMMON_TOKEN    b;
    pANTLR3_COMMON_TOKEN    a;
    pANTLR3_COMMON_TOKEN    rgb;

    /* Initialize rule variables
     */


    r       = NULL;
    g       = NULL;
    b       = NULL;
    a       = NULL;
    rgb       = NULL;

    {
        {
            //  RadialGradientColor.g:130:6: ( ( 'rgba(' r= FLOAT ',' g= FLOAT ',' b= FLOAT ',' a= FLOAT ')' ) | ( 'rgba(' rgb= HEXINT ',' a= FLOAT ')' ) )

            ANTLR3_UINT32 alt3;

            alt3 = 2;

            switch ( LA(1) ) {
            case 19: {
                switch ( LA(2) ) {
                case FLOAT: {
                    alt3 = 1;
                }
                break;
                case HEXINT: {
                    alt3 = 2;
                }
                break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 3;
                    EXCEPTION->state        = 1;


                    goto rulergbaEx;
                }

            }
            break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto rulergbaEx;
            }

            switch (alt3) {
            case 1:
                // RadialGradientColor.g:131:2: ( 'rgba(' r= FLOAT ',' g= FLOAT ',' b= FLOAT ',' a= FLOAT ')' )
            {
                // RadialGradientColor.g:131:2: ( 'rgba(' r= FLOAT ',' g= FLOAT ',' b= FLOAT ',' a= FLOAT ')' )
                // RadialGradientColor.g:131:3: 'rgba(' r= FLOAT ',' g= FLOAT ',' b= FLOAT ',' a= FLOAT ')'
                {
                    MATCHT(19, &FOLLOW_19_in_rgba673);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    r = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_rgba677);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    MATCHT(15, &FOLLOW_15_in_rgba679);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    g = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_rgba683);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    MATCHT(15, &FOLLOW_15_in_rgba685);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    b = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_rgba689);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    MATCHT(15, &FOLLOW_15_in_rgba691);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    a = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_rgba695);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    MATCHT(20, &FOLLOW_20_in_rgba697);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }


                }

                {

                    (SCOPE_TOP(ColorSet))->red = pu8tof((r->getText(r))->chars);
                    (SCOPE_TOP(ColorSet))->green = pu8tof((g->getText(g))->chars);
                    (SCOPE_TOP(ColorSet))->blue = pu8tof((b->getText(b))->chars);
                    (SCOPE_TOP(ColorSet))->alpha = pu8tof((a->getText(a))->chars);

                }

            }
            break;
            case 2:
                // RadialGradientColor.g:138:2: ( 'rgba(' rgb= HEXINT ',' a= FLOAT ')' )
            {
                // RadialGradientColor.g:138:2: ( 'rgba(' rgb= HEXINT ',' a= FLOAT ')' )
                // RadialGradientColor.g:138:3: 'rgba(' rgb= HEXINT ',' a= FLOAT ')'
                {
                    MATCHT(19, &FOLLOW_19_in_rgba708);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    rgb = (pANTLR3_COMMON_TOKEN) MATCHT(HEXINT, &FOLLOW_HEXINT_in_rgba712);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    MATCHT(15, &FOLLOW_15_in_rgba714);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    a = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_rgba718);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }

                    MATCHT(20, &FOLLOW_20_in_rgba720);
                    if  (HASEXCEPTION()) {
                        goto rulergbaEx;
                    }


                }

                {

                    parse3values((rgb->getText(rgb))->chars, &( (SCOPE_TOP(ColorSet))->red), &( (SCOPE_TOP(ColorSet))->green), &(   (SCOPE_TOP(ColorSet))->blue));
                    (SCOPE_TOP(ColorSet))->alpha = pu8tof((a->getText(a))->chars);

                }

            }
            break;

            }
        }
    }


    // This is where rules clean up and exit
    //
    goto rulergbaEx; /* Prevent compiler warnings */
rulergbaEx:
    ;

    if (HASEXCEPTION()) {
        PREPORTERROR();
        PRECOVER();
    }


    return ;
}
/* $ANTLR end rgba */

/**
 * $ANTLR start hsba
 * RadialGradientColor.g:144:1: hsba : 'hsba(' h= FLOAT ',' s= FLOAT ',' b= FLOAT ',' a= FLOAT ')' ;
 */
static void
hsba(pRadialGradientColorParser ctx)
{
    pANTLR3_COMMON_TOKEN    h;
    pANTLR3_COMMON_TOKEN    s;
    pANTLR3_COMMON_TOKEN    b;
    pANTLR3_COMMON_TOKEN    a;

    /* Initialize rule variables
     */


    h       = NULL;
    s       = NULL;
    b       = NULL;
    a       = NULL;

    {
        // RadialGradientColor.g:144:6: ( 'hsba(' h= FLOAT ',' s= FLOAT ',' b= FLOAT ',' a= FLOAT ')' )
        // RadialGradientColor.g:145:2: 'hsba(' h= FLOAT ',' s= FLOAT ',' b= FLOAT ',' a= FLOAT ')'
        {
            MATCHT(21, &FOLLOW_21_in_hsba735);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            h = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_hsba739);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            MATCHT(15, &FOLLOW_15_in_hsba741);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            s = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_hsba745);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            MATCHT(15, &FOLLOW_15_in_hsba747);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            b = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_hsba751);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            MATCHT(15, &FOLLOW_15_in_hsba753);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            a = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_hsba757);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            MATCHT(20, &FOLLOW_20_in_hsba759);
            if  (HASEXCEPTION()) {
                goto rulehsbaEx;
            }

            {

                HsvToRgb(
                    pu8tof((h->getText(h))->chars),
                    pu8tof((s->getText(s))->chars),
                    pu8tof((b->getText(b))->chars),
                    (SCOPE_TOP(ColorSet))->red,
                    (SCOPE_TOP(ColorSet))->green,
                    (SCOPE_TOP(ColorSet))->blue);
                (SCOPE_TOP(ColorSet))->alpha = pu8tof((a->getText(a))->chars);

            }

        }

    }


    // This is where rules clean up and exit
    //
    goto rulehsbaEx; /* Prevent compiler warnings */
rulehsbaEx:
    ;

    if (HASEXCEPTION()) {
        PREPORTERROR();
        PRECOVER();
    }


    return ;
}
/* $ANTLR end hsba */

/**
 * $ANTLR start pos
 * RadialGradientColor.g:158:1: pos : value= FLOAT ;
 */
static void
pos(pRadialGradientColorParser ctx)
{
    pANTLR3_COMMON_TOKEN    value;

    /* Initialize rule variables
     */


    value       = NULL;

    {
        // RadialGradientColor.g:158:5: (value= FLOAT )
        // RadialGradientColor.g:158:7: value= FLOAT
        {
            value = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_pos774);
            if  (HASEXCEPTION()) {
                goto ruleposEx;
            }

            {

                (SCOPE_TOP(ColorSet))->position = pu8tof((value->getText(value))->chars);

            }

        }

    }


    // This is where rules clean up and exit
    //
    goto ruleposEx; /* Prevent compiler warnings */
ruleposEx:
    ;

    if (HASEXCEPTION()) {
        PREPORTERROR();
        PRECOVER();
    }


    return ;
}
/* $ANTLR end pos */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
