#ifndef NX_COLOR_GRADIENTDIRECTION_H_
#define NX_COLOR_GRADIENTDIRECTION_H_

namespace nx
{
namespace color
{
enum GRADIENT_DIRECTION {
    GRADIENT_DIRECTION_TOP_BOTTOM,
    GRADIENT_DIRECTION_TOPLEFT_TO_BOTTOMRIGHT,
    GRADIENT_DIRECTION_TOPRIGHT_TO_BOTTOMLEFT,
};
}
}

#endif // NX_COLOR_GRADIENTDIRECTION_H_